# Generated by Django 5.2.4 on 2025-07-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santhosh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='IMAGE',
            field=models.ImageField(blank=True, default='blank.png', null=True, upload_to=''),
        ),
    ]
